# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('gpio_config.json', '.'),
        ('pref.json', '.'),
        ('console_deck_v2_arduino_code', 'console_deck_v2_arduino_code'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'pygame',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'pyperclip',
        'serial',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'ctypes',
        'ctypes.wintypes',
        'threading',
        'json',
        'os',
        'sys',
        'time',
        'subprocess',
        'webbrowser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ConsoleDeck',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
